// Ticker + company name pairs for autocomplete. Kept separate from the
// backend's data/nifty50.py (Python) since this is a tiny, frontend-only
// convenience list - not the source of truth for which tickers are valid
// (the backend/tools.py list is), just enough for a helpful autocomplete.
export const NIFTY50_META = [
  { ticker: "ADANIENT.NS", name: "Adani Enterprises" },
  { ticker: "ADANIPORTS.NS", name: "Adani Ports" },
  { ticker: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
  { ticker: "ASIANPAINT.NS", name: "Asian Paints" },
  { ticker: "AXISBANK.NS", name: "Axis Bank" },
  { ticker: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { ticker: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
  { ticker: "BPCL.NS", name: "Bharat Petroleum" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { ticker: "BRITANNIA.NS", name: "Britannia" },
  { ticker: "CIPLA.NS", name: "Cipla" },
  { ticker: "COALINDIA.NS", name: "Coal India" },
  { ticker: "DIVISLAB.NS", name: "Divi's Labs" },
  { ticker: "DRREDDY.NS", name: "Dr Reddy's" },
  { ticker: "EICHERMOT.NS", name: "Eicher Motors" },
  { ticker: "GRASIM.NS", name: "Grasim" },
  { ticker: "HCLTECH.NS", name: "HCL Technologies" },
  { ticker: "HDFCBANK.NS", name: "HDFC Bank" },
  { ticker: "HDFCLIFE.NS", name: "HDFC Life" },
  { ticker: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
  { ticker: "HINDALCO.NS", name: "Hindalco" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { ticker: "ICICIBANK.NS", name: "ICICI Bank" },
  { ticker: "ITC.NS", name: "ITC" },
  { ticker: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { ticker: "INFY.NS", name: "Infosys" },
  { ticker: "JSWSTEEL.NS", name: "JSW Steel" },
  { ticker: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { ticker: "LTM.NS", name: "LTIMindtree" },
  { ticker: "LT.NS", name: "Larsen & Toubro" },
  { ticker: "M&M.NS", name: "Mahindra & Mahindra" },
  { ticker: "MARUTI.NS", name: "Maruti Suzuki" },
  { ticker: "NTPC.NS", name: "NTPC" },
  { ticker: "NESTLEIND.NS", name: "Nestle India" },
  { ticker: "ONGC.NS", name: "ONGC" },
  { ticker: "POWERGRID.NS", name: "Power Grid" },
  { ticker: "RELIANCE.NS", name: "Reliance Industries" },
  { ticker: "SBILIFE.NS", name: "SBI Life" },
  { ticker: "SBIN.NS", name: "State Bank of India" },
  { ticker: "SUNPHARMA.NS", name: "Sun Pharma" },
  { ticker: "TCS.NS", name: "Tata Consultancy Services" },
  { ticker: "TATACONSUM.NS", name: "Tata Consumer" },
  { ticker: "TMPV.NS", name: "Tata Motors Passenger Vehicles" },
  { ticker: "TATASTEEL.NS", name: "Tata Steel" },
  { ticker: "TECHM.NS", name: "Tech Mahindra" },
  { ticker: "TITAN.NS", name: "Titan" },
  { ticker: "UPL.NS", name: "UPL" },
  { ticker: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { ticker: "WIPRO.NS", name: "Wipro" },
];